# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  # vmImage: 'win1803'
  # vmImage: 'ubuntu-16.04'
  # vmImage: 'macOS-10.13'
  vmImage: windows-2019

steps:
- task: katalonTask@0
  inputs:
    version: '7.0.10'
    executeArgs: '-retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="default" -browserType="Firefox" -apiKey="b279faef-0a5a-4aa5-8cff-ebc81466ac8c"'