# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  # vmImage: 'win1803'
  # vmImage: 'ubuntu-16.04'
  # vmImage: 'macOS-10.13'
  vmImage: windows-2019

steps:
  - task: katalondevopsextensionplugin@0
    inputs:
      version: "6.1.1"
      location: ''
      executeArgs: -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="default" -browserType="Firefox"
      x11Display: ''
      xvfbConfiguration: -a -n 0 -s "screen 0 1024x768x24"