# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
# - script: docker pull katalonstudio/katalon
  # displayName: 'Pull katalon sudio images'
# - script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
  # displayName: 'Runnning Katalon TS_RegressionTest'
# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'JUnit Report' 
#     targetPath: report/
# Download version: 5.10
# Use: ...

  - task: buildandreleasetask@0
    inputs:
      # samplestring: "Anh Tuan Tran"
      version: "5.10.100 sample"
      location: 'katalon studioo'
      executeArgs: '-reportFolder="Reports" -reportFileName="report" -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -browserType="Chrome"'
      x11Display: 'null'
      xvfbConfiguration: 'null'
    